<?xml version="1.0" encoding="utf-8"?><Database Name="Bystronic" Class="BystronicDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=lchpid1;Initial Catalog=Bystronic;Integrated Security=True" SettingsObjectName="BystronicDataService.Properties.Settings" SettingsPropertyName="BystronicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductList" Member="ProductLists">
    <Type Name="ProductList">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Tooling" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductManager" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Template" Member="Templates">
    <Type Name="Template">
      <Column Name="TemplateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Formula" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PMADID" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Tooling" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerList" Member="CustomerLists">
    <Type Name="CustomerList">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAPNumber" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTypeList" Member="ProductTypeLists">
    <Type Name="ProductTypeList">
      <Column Name="ProductTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItemList" Member="OrderItemLists">
    <Type Name="OrderItemList">
      <Column Name="OrderItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ToolingPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SalesPeopleList" Member="SalesPeopleLists">
    <Type Name="SalesPeopleList">
      <Column Name="SalesPersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YTDSales" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="CostCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalesGoals" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderList" Member="OrderLists">
    <Type Name="OrderList">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateOfSale" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PONumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalProductCost" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="DiscountAmount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPerc" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="DealerCommission" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="RMCommission" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="PMCommission" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReleasedBy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ReleasedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrackingNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalesPerson2ADID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TemplateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaidBy" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PaidDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayrollDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SalesPersonADID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalesOrder" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EstimatedShipDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinalPaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RSMADID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayRSMCommission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetOrderItemsByOrderID" Method="GetOrderItemsByOrderID">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetOrderItemsByOrderIDResult">
      <Column Name="OrderItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateOrderItem" Method="UpdateOrderItem">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateAdded" Parameter="dateAdded" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListPrice" Parameter="listPrice" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteOrderItemsByOrderID" Method="DeleteOrderItemsByOrderID">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteOrderByOrderID" Method="DeleteOrderByOrderID">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCustomer" Method="UpdateCustomer">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RegionID" Parameter="regionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SAPNumber" Parameter="sAPNumber" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCustomerWOOrder" Method="DeleteCustomerWOOrder">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="DeleteCustomerWOOrderResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddProduct" Method="AddProduct">
    <Parameter Name="ProductTypeID" Parameter="productTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="Tooling" Parameter="tooling" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ProductManager" Parameter="productManager" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateProduct" Method="UpdateProduct">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductTypeID" Parameter="productTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="Tooling" Parameter="tooling" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ProductManager" Parameter="productManager" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteProductWOOrder" Method="DeleteProductWOOrder">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <ElementType Name="DeleteProductWOOrderResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddOrderItem" Method="AddOrderItem">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateAdded" Parameter="dateAdded" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListPrice" Parameter="listPrice" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="ToolingPrice" Parameter="toolingPrice" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddCustomer" Method="AddCustomer">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SAPNo" Parameter="sAPNo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetYTDBySalesmanOrderDate" Method="GetYTDBySalesmanOrderDate">
    <Parameter Name="ADID" Parameter="aDID" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="orderid" Type="System.Int32" DbType="Int" />
    <Parameter Name="orderDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="GetYTDBySalesmanOrderDateResult">
      <Column Name="YTD" Type="System.Decimal" DbType="Decimal(38,4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteSalesman" Method="DeleteSalesman">
    <Parameter Name="ADID" Parameter="aDID" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="DeleteSalesmanResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddSalesman" Method="AddSalesman">
    <Parameter Name="ADID" Parameter="aDID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="SalesRepID" Parameter="salesRepID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RegionName" Parameter="regionName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesGoalAmount" Parameter="salesGoalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="YTDSalesAmountBaseline" Parameter="yTDSalesAmountBaseline" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="CostCenter" Parameter="costCenter" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesGoals" Parameter="salesGoals" Type="System.String" DbType="VarChar(5000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSalesman" Method="UpdateSalesman">
    <Parameter Name="OLDADID" Parameter="oLDADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADID" Parameter="aDID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="SalesRepID" Parameter="salesRepID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RegionName" Parameter="regionName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesGoalAmount" Parameter="salesGoalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="YTDSalesAmountBaseline" Parameter="yTDSalesAmountBaseline" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="CostCenter" Parameter="costCenter" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesGoals" Parameter="salesGoals" Type="System.String" DbType="VarChar(5000)" />
    <ElementType Name="UpdateSalesmanResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddOrder" Method="AddOrder">
    <Parameter Name="DateEntered" Parameter="dateEntered" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateOfSale" Parameter="dateOfSale" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SalesPersonADID" Parameter="salesPersonADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesPerson2ADID" Parameter="salesPerson2ADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RSMADID" Parameter="rSMADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PayRSMCommission" Parameter="payRSMCommission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PONumber" Parameter="pONumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TotalProductCost" Parameter="totalProductCost" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="SalePrice" Parameter="salePrice" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DiscountAmount" Parameter="discountAmount" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DiscountPerc" Parameter="discountPerc" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DealerCommission" Parameter="dealerCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="RMCommission" Parameter="rMCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="PMCommission" Parameter="pMCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="Comments" Parameter="comments" Type="System.String" DbType="VarChar(5000)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="ApprovedDate" Parameter="approvedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ReleasedBy" Parameter="releasedBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="ReleasedDate" Parameter="releasedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PaidBy" Parameter="paidBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="PaidDate" Parameter="paidDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PayrollDate" Parameter="payrollDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TrackingNumber" Parameter="trackingNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TemplateID" Parameter="templateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SalesOrder" Parameter="salesOrder" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EstimatedShipDate" Parameter="estimatedShipDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FinalPaymentDate" Parameter="finalPaymentDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateOrder" Method="UpdateOrder">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateEntered" Parameter="dateEntered" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateOfSale" Parameter="dateOfSale" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SalesPersonADID" Parameter="salesPersonADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SalesPerson2ADID" Parameter="salesPerson2ADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RSMADID" Parameter="rSMADID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PayRSMCommission" Parameter="payRSMCommission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PONumber" Parameter="pONumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TotalProductCost" Parameter="totalProductCost" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="SalePrice" Parameter="salePrice" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DiscountAmount" Parameter="discountAmount" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DiscountPerc" Parameter="discountPerc" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="DealerCommission" Parameter="dealerCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="RMCommission" Parameter="rMCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="PMCommission" Parameter="pMCommission" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="Comments" Parameter="comments" Type="System.String" DbType="VarChar(5000)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ApprovedBy" Parameter="approvedBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="ApprovedDate" Parameter="approvedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ReleasedBy" Parameter="releasedBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="ReleasedDate" Parameter="releasedDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PaidBy" Parameter="paidBy" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="PaidDate" Parameter="paidDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PayrollDate" Parameter="payrollDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TrackingNumber" Parameter="trackingNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TemplateID" Parameter="templateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SalesOrder" Parameter="salesOrder" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EstimatedShipDate" Parameter="estimatedShipDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FinalPaymentDate" Parameter="finalPaymentDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteGridByUserAndGridName" Method="DeleteGridByUserAndGridName">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GridName" Parameter="gridName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddUpdateUsersGridColumns" Method="AddUpdateUsersGridColumns">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GridName" Parameter="gridName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NewGridName" Parameter="newGridName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Columns" Parameter="columns" Type="System.String" DbType="VarChar(1500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetgRIDcolumnsByUser" Method="GetgRIDcolumnsByUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GridName" Parameter="gridName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetgRIDcolumnsByUserResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gridcolumns" Type="System.String" DbType="VarChar(1500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetViewsByUser" Method="GetViewsByUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetViewsByUserResult">
      <Column Name="gridname" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gridcolumns" Type="System.String" DbType="VarChar(1500)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>