#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BystronicDataService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bystronic")]
	public partial class BystronicDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTemplate(Template instance);
    partial void UpdateTemplate(Template instance);
    partial void DeleteTemplate(Template instance);
    #endregion
		
		public BystronicDataDataContext() : 
				base(global::BystronicDataService.Properties.Settings.Default.BystronicConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductList> ProductLists
		{
			get
			{
				return this.GetTable<ProductList>();
			}
		}
		
		public System.Data.Linq.Table<Template> Templates
		{
			get
			{
				return this.GetTable<Template>();
			}
		}
		
		public System.Data.Linq.Table<CustomerList> CustomerLists
		{
			get
			{
				return this.GetTable<CustomerList>();
			}
		}
		
		public System.Data.Linq.Table<ProductTypeList> ProductTypeLists
		{
			get
			{
				return this.GetTable<ProductTypeList>();
			}
		}
		
		public System.Data.Linq.Table<OrderItemList> OrderItemLists
		{
			get
			{
				return this.GetTable<OrderItemList>();
			}
		}
		
		public System.Data.Linq.Table<SalesPeopleList> SalesPeopleLists
		{
			get
			{
				return this.GetTable<SalesPeopleList>();
			}
		}
		
		public System.Data.Linq.Table<OrderList> OrderLists
		{
			get
			{
				return this.GetTable<OrderList>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOrderItemsByOrderID")]
		public ISingleResult<GetOrderItemsByOrderIDResult> GetOrderItemsByOrderID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((ISingleResult<GetOrderItemsByOrderIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateOrderItem")]
		public int UpdateOrderItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateAdded", DbType="DateTime")] System.Nullable<System.DateTime> dateAdded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListPrice", DbType="Decimal(18,4)")] System.Nullable<decimal> listPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, dateAdded, productID, listPrice);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteOrderItemsByOrderID")]
		public int DeleteOrderItemsByOrderID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteOrderByOrderID")]
		public int DeleteOrderByOrderID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateCustomer")]
		public int UpdateCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(250)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="VarChar(50)")] string zip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionID", DbType="Int")] System.Nullable<int> regionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNumber", DbType="VarChar(150)")] string sAPNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, name, address, city, state, zip, regionID, sAPNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCustomerWOOrder")]
		public ISingleResult<DeleteCustomerWOOrderResult> DeleteCustomerWOOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID);
			return ((ISingleResult<DeleteCustomerWOOrderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddProduct")]
		public int AddProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductTypeID", DbType="Int")] System.Nullable<int> productTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Decimal(18,4)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tooling", DbType="Bit")] System.Nullable<bool> tooling, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductManager", DbType="VarChar(50)")] string productManager)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productTypeID, name, price, tooling, productManager);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateProduct")]
		public int UpdateProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductTypeID", DbType="Int")] System.Nullable<int> productTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Decimal(18,4)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tooling", DbType="Bit")] System.Nullable<bool> tooling, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductManager", DbType="VarChar(50)")] string productManager)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID, productTypeID, name, price, tooling, productManager);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteProductWOOrder")]
		public ISingleResult<DeleteProductWOOrderResult> DeleteProductWOOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID);
			return ((ISingleResult<DeleteProductWOOrderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddOrderItem")]
		public int AddOrderItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateAdded", DbType="DateTime")] System.Nullable<System.DateTime> dateAdded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListPrice", DbType="Decimal(18,4)")] System.Nullable<decimal> listPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToolingPrice", DbType="Decimal(18,4)")] System.Nullable<decimal> toolingPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, dateAdded, productID, listPrice, toolingPrice);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddCustomer")]
		public int AddCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(250)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="VarChar(50)")] string zip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNo", DbType="VarChar(50)")] string sAPNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, address, city, state, zip, sAPNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetYTDBySalesmanOrderDate")]
		public ISingleResult<GetYTDBySalesmanOrderDateResult> GetYTDBySalesmanOrderDate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADID", DbType="VarChar(1)")] string aDID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orderid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> orderDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aDID, orderid, orderDate);
			return ((ISingleResult<GetYTDBySalesmanOrderDateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteSalesman")]
		public ISingleResult<DeleteSalesmanResult> DeleteSalesman([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADID", DbType="VarChar(50)")] string aDID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aDID);
			return ((ISingleResult<DeleteSalesmanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddSalesman")]
		public int AddSalesman([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADID", DbType="VarChar(50)")] string aDID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(150)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(150)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="VarChar(50)")] string salesRepID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionName", DbType="VarChar(50)")] string regionName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesGoalAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> salesGoalAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YTDSalesAmountBaseline", DbType="Decimal(18,4)")] System.Nullable<decimal> yTDSalesAmountBaseline, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostCenter", DbType="VarChar(50)")] string costCenter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesGoals", DbType="VarChar(5000)")] string salesGoals)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aDID, firstName, lastName, salesRepID, regionName, type, salesGoalAmount, yTDSalesAmountBaseline, costCenter, salesGoals);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateSalesman")]
		public ISingleResult<UpdateSalesmanResult> UpdateSalesman([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLDADID", DbType="VarChar(50)")] string oLDADID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADID", DbType="VarChar(50)")] string aDID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(150)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(150)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRepID", DbType="VarChar(50)")] string salesRepID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionName", DbType="VarChar(50)")] string regionName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesGoalAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> salesGoalAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YTDSalesAmountBaseline", DbType="Decimal(18,4)")] System.Nullable<decimal> yTDSalesAmountBaseline, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostCenter", DbType="VarChar(50)")] string costCenter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesGoals", DbType="VarChar(5000)")] string salesGoals)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oLDADID, aDID, firstName, lastName, salesRepID, regionName, type, salesGoalAmount, yTDSalesAmountBaseline, costCenter, salesGoals);
			return ((ISingleResult<UpdateSalesmanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddOrder")]
		public int AddOrder(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateEntered", DbType="DateTime")] System.Nullable<System.DateTime> dateEntered, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfSale", DbType="DateTime")] System.Nullable<System.DateTime> dateOfSale, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPersonADID", DbType="VarChar(50)")] string salesPersonADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPerson2ADID", DbType="VarChar(50)")] string salesPerson2ADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RSMADID", DbType="VarChar(50)")] string rSMADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayRSMCommission", DbType="Bit")] System.Nullable<bool> payRSMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PONumber", DbType="VarChar(50)")] string pONumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalProductCost", DbType="Decimal(18,4)")] System.Nullable<decimal> totalProductCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalePrice", DbType="Decimal(18,4)")] System.Nullable<decimal> salePrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> discountAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountPerc", DbType="Decimal(18,4)")] System.Nullable<decimal> discountPerc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DealerCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> dealerCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RMCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> rMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PMCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> pMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(5000)")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(50)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprovedBy", DbType="VarChar(250)")] string approvedBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprovedDate", DbType="DateTime")] System.Nullable<System.DateTime> approvedDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReleasedBy", DbType="VarChar(250)")] string releasedBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReleasedDate", DbType="DateTime")] System.Nullable<System.DateTime> releasedDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidBy", DbType="VarChar(250)")] string paidBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidDate", DbType="DateTime")] System.Nullable<System.DateTime> paidDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayrollDate", DbType="Date")] System.Nullable<System.DateTime> payrollDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingNumber", DbType="VarChar(50)")] string trackingNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemplateID", DbType="Int")] System.Nullable<int> templateID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesOrder", DbType="VarChar(50)")] string salesOrder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstimatedShipDate", DbType="Date")] System.Nullable<System.DateTime> estimatedShipDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalPaymentDate", DbType="Date")] System.Nullable<System.DateTime> finalPaymentDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateEntered, dateOfSale, salesPersonADID, salesPerson2ADID, rSMADID, payRSMCommission, customerID, pONumber, totalProductCost, salePrice, discountAmount, discountPerc, dealerCommission, rMCommission, pMCommission, comments, status, approvedBy, approvedDate, releasedBy, releasedDate, paidBy, paidDate, payrollDate, trackingNumber, templateID, salesOrder, estimatedShipDate, finalPaymentDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateOrder")]
		public int UpdateOrder(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateEntered", DbType="DateTime")] System.Nullable<System.DateTime> dateEntered, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfSale", DbType="DateTime")] System.Nullable<System.DateTime> dateOfSale, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPersonADID", DbType="VarChar(50)")] string salesPersonADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPerson2ADID", DbType="VarChar(50)")] string salesPerson2ADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RSMADID", DbType="VarChar(50)")] string rSMADID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayRSMCommission", DbType="Bit")] System.Nullable<bool> payRSMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PONumber", DbType="VarChar(50)")] string pONumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalProductCost", DbType="Decimal(18,4)")] System.Nullable<decimal> totalProductCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalePrice", DbType="Decimal(18,4)")] System.Nullable<decimal> salePrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> discountAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountPerc", DbType="Decimal(18,4)")] System.Nullable<decimal> discountPerc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DealerCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> dealerCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RMCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> rMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PMCommission", DbType="Decimal(18,4)")] System.Nullable<decimal> pMCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(5000)")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(50)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprovedBy", DbType="VarChar(250)")] string approvedBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprovedDate", DbType="DateTime")] System.Nullable<System.DateTime> approvedDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReleasedBy", DbType="VarChar(250)")] string releasedBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReleasedDate", DbType="DateTime")] System.Nullable<System.DateTime> releasedDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidBy", DbType="VarChar(250)")] string paidBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaidDate", DbType="DateTime")] System.Nullable<System.DateTime> paidDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PayrollDate", DbType="Date")] System.Nullable<System.DateTime> payrollDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingNumber", DbType="VarChar(50)")] string trackingNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemplateID", DbType="Int")] System.Nullable<int> templateID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesOrder", DbType="VarChar(50)")] string salesOrder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstimatedShipDate", DbType="Date")] System.Nullable<System.DateTime> estimatedShipDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalPaymentDate", DbType="Date")] System.Nullable<System.DateTime> finalPaymentDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, dateEntered, dateOfSale, salesPersonADID, salesPerson2ADID, rSMADID, payRSMCommission, customerID, pONumber, totalProductCost, salePrice, discountAmount, discountPerc, dealerCommission, rMCommission, pMCommission, comments, status, approvedBy, approvedDate, releasedBy, releasedDate, paidBy, paidDate, payrollDate, trackingNumber, templateID, salesOrder, estimatedShipDate, finalPaymentDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteGridByUserAndGridName")]
		public int DeleteGridByUserAndGridName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddUpdateUsersGridColumns")]
		public int AddUpdateUsersGridColumns([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewGridName", DbType="VarChar(50)")] string newGridName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Columns", DbType="VarChar(1500)")] string columns)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName, newGridName, columns);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetgRIDcolumnsByUser")]
		public ISingleResult<GetgRIDcolumnsByUserResult> GetgRIDcolumnsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName);
			return ((ISingleResult<GetgRIDcolumnsByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetViewsByUser")]
		public ISingleResult<GetViewsByUserResult> GetViewsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<GetViewsByUserResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductList")]
	public partial class ProductList
	{
		
		private int _ProductID;
		
		private System.Nullable<int> _ProductTypeID;
		
		private string _Name;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<bool> _Tooling;
		
		private string _ProductManager;
		
		public ProductList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeID", DbType="Int")]
		public System.Nullable<int> ProductTypeID
		{
			get
			{
				return this._ProductTypeID;
			}
			set
			{
				if ((this._ProductTypeID != value))
				{
					this._ProductTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tooling", DbType="Bit")]
		public System.Nullable<bool> Tooling
		{
			get
			{
				return this._Tooling;
			}
			set
			{
				if ((this._Tooling != value))
				{
					this._Tooling = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductManager", DbType="VarChar(50)")]
		public string ProductManager
		{
			get
			{
				return this._ProductManager;
			}
			set
			{
				if ((this._ProductManager != value))
				{
					this._ProductManager = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Template")]
	public partial class Template : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TemplateID;
		
		private string _Formula;
		
		private string _Name;
		
		private string _PMADID;
		
		private System.Nullable<bool> _Tooling;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTemplateIDChanging(int value);
    partial void OnTemplateIDChanged();
    partial void OnFormulaChanging(string value);
    partial void OnFormulaChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPMADIDChanging(string value);
    partial void OnPMADIDChanged();
    partial void OnToolingChanging(System.Nullable<bool> value);
    partial void OnToolingChanged();
    #endregion
		
		public Template()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TemplateID
		{
			get
			{
				return this._TemplateID;
			}
			set
			{
				if ((this._TemplateID != value))
				{
					this.OnTemplateIDChanging(value);
					this.SendPropertyChanging();
					this._TemplateID = value;
					this.SendPropertyChanged("TemplateID");
					this.OnTemplateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formula", DbType="VarChar(MAX)")]
		public string Formula
		{
			get
			{
				return this._Formula;
			}
			set
			{
				if ((this._Formula != value))
				{
					this.OnFormulaChanging(value);
					this.SendPropertyChanging();
					this._Formula = value;
					this.SendPropertyChanged("Formula");
					this.OnFormulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMADID", DbType="VarChar(250)")]
		public string PMADID
		{
			get
			{
				return this._PMADID;
			}
			set
			{
				if ((this._PMADID != value))
				{
					this.OnPMADIDChanging(value);
					this.SendPropertyChanging();
					this._PMADID = value;
					this.SendPropertyChanged("PMADID");
					this.OnPMADIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tooling", DbType="Bit")]
		public System.Nullable<bool> Tooling
		{
			get
			{
				return this._Tooling;
			}
			set
			{
				if ((this._Tooling != value))
				{
					this.OnToolingChanging(value);
					this.SendPropertyChanging();
					this._Tooling = value;
					this.SendPropertyChanged("Tooling");
					this.OnToolingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerList")]
	public partial class CustomerList
	{
		
		private int _CustomerID;
		
		private string _Name;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private System.Nullable<int> _RegionID;
		
		private string _Zip;
		
		private string _SAPNumber;
		
		public CustomerList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPNumber", DbType="VarChar(150)")]
		public string SAPNumber
		{
			get
			{
				return this._SAPNumber;
			}
			set
			{
				if ((this._SAPNumber != value))
				{
					this._SAPNumber = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductTypeList")]
	public partial class ProductTypeList
	{
		
		private int _ProductTypeID;
		
		private string _Type;
		
		public ProductTypeList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ProductTypeID
		{
			get
			{
				return this._ProductTypeID;
			}
			set
			{
				if ((this._ProductTypeID != value))
				{
					this._ProductTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderItemList")]
	public partial class OrderItemList
	{
		
		private int _OrderItemID;
		
		private System.Nullable<int> _OrderID;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private int _ProductID;
		
		private System.Nullable<decimal> _ListPrice;
		
		private System.Nullable<decimal> _ToolingPrice;
		
		public OrderItemList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderItemID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OrderItemID
		{
			get
			{
				return this._OrderItemID;
			}
			set
			{
				if ((this._OrderItemID != value))
				{
					this._OrderItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int")]
		public System.Nullable<int> OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListPrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ListPrice
		{
			get
			{
				return this._ListPrice;
			}
			set
			{
				if ((this._ListPrice != value))
				{
					this._ListPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolingPrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ToolingPrice
		{
			get
			{
				return this._ToolingPrice;
			}
			set
			{
				if ((this._ToolingPrice != value))
				{
					this._ToolingPrice = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesPeopleList")]
	public partial class SalesPeopleList
	{
		
		private int _SalesPersonID;
		
		private string _ADID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<int> _RegionID;
		
		private string _Type;
		
		private string _Region;
		
		private System.Nullable<decimal> _YTDSales;
		
		private string _CostCenter;
		
		private string _SalesGoals;
		
		public SalesPeopleList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPersonID", DbType="Int NOT NULL")]
		public int SalesPersonID
		{
			get
			{
				return this._SalesPersonID;
			}
			set
			{
				if ((this._SalesPersonID != value))
				{
					this._SalesPersonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ADID
		{
			get
			{
				return this._ADID;
			}
			set
			{
				if ((this._ADID != value))
				{
					this._ADID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="VarChar(50)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTDSales", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> YTDSales
		{
			get
			{
				return this._YTDSales;
			}
			set
			{
				if ((this._YTDSales != value))
				{
					this._YTDSales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCenter", DbType="VarChar(50)")]
		public string CostCenter
		{
			get
			{
				return this._CostCenter;
			}
			set
			{
				if ((this._CostCenter != value))
				{
					this._CostCenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesGoals", DbType="VarChar(5000)")]
		public string SalesGoals
		{
			get
			{
				return this._SalesGoals;
			}
			set
			{
				if ((this._SalesGoals != value))
				{
					this._SalesGoals = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderList")]
	public partial class OrderList
	{
		
		private int _OrderID;
		
		private System.Nullable<System.DateTime> _DateEntered;
		
		private System.Nullable<System.DateTime> _DateOfSale;
		
		private System.Nullable<int> _CustomerID;
		
		private string _PONumber;
		
		private System.Nullable<decimal> _TotalProductCost;
		
		private System.Nullable<decimal> _SalePrice;
		
		private decimal _DiscountAmount;
		
		private System.Nullable<decimal> _DiscountPerc;
		
		private System.Nullable<decimal> _DealerCommission;
		
		private System.Nullable<decimal> _RMCommission;
		
		private System.Nullable<decimal> _PMCommission;
		
		private string _Comments;
		
		private string _ApprovedBy;
		
		private System.Nullable<System.DateTime> _ApprovedDate;
		
		private string _ReleasedBy;
		
		private System.Nullable<System.DateTime> _ReleasedDate;
		
		private string _TrackingNumber;
		
		private string _SalesPerson2ADID;
		
		private System.Nullable<int> _TemplateID;
		
		private string _Status;
		
		private string _PaidBy;
		
		private System.Nullable<System.DateTime> _PaidDate;
		
		private System.Nullable<System.DateTime> _PayrollDate;
		
		private string _SalesPersonADID;
		
		private string _SalesOrder;
		
		private System.Nullable<System.DateTime> _EstimatedShipDate;
		
		private System.Nullable<System.DateTime> _FinalPaymentDate;
		
		private string _RSMADID;
		
		private System.Nullable<bool> _PayRSMCommission;
		
		public OrderList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEntered", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEntered
		{
			get
			{
				return this._DateEntered;
			}
			set
			{
				if ((this._DateEntered != value))
				{
					this._DateEntered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfSale", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfSale
		{
			get
			{
				return this._DateOfSale;
			}
			set
			{
				if ((this._DateOfSale != value))
				{
					this._DateOfSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
		public System.Nullable<int> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONumber", DbType="VarChar(50)")]
		public string PONumber
		{
			get
			{
				return this._PONumber;
			}
			set
			{
				if ((this._PONumber != value))
				{
					this._PONumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductCost", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> TotalProductCost
		{
			get
			{
				return this._TotalProductCost;
			}
			set
			{
				if ((this._TotalProductCost != value))
				{
					this._TotalProductCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SalePrice
		{
			get
			{
				return this._SalePrice;
			}
			set
			{
				if ((this._SalePrice != value))
				{
					this._SalePrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountAmount", DbType="Decimal(18,4) NOT NULL")]
		public decimal DiscountAmount
		{
			get
			{
				return this._DiscountAmount;
			}
			set
			{
				if ((this._DiscountAmount != value))
				{
					this._DiscountAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountPerc", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> DiscountPerc
		{
			get
			{
				return this._DiscountPerc;
			}
			set
			{
				if ((this._DiscountPerc != value))
				{
					this._DiscountPerc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerCommission", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> DealerCommission
		{
			get
			{
				return this._DealerCommission;
			}
			set
			{
				if ((this._DealerCommission != value))
				{
					this._DealerCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCommission", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> RMCommission
		{
			get
			{
				return this._RMCommission;
			}
			set
			{
				if ((this._RMCommission != value))
				{
					this._RMCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMCommission", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> PMCommission
		{
			get
			{
				return this._PMCommission;
			}
			set
			{
				if ((this._PMCommission != value))
				{
					this._PMCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(5000)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="VarChar(250)")]
		public string ApprovedBy
		{
			get
			{
				return this._ApprovedBy;
			}
			set
			{
				if ((this._ApprovedBy != value))
				{
					this._ApprovedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ApprovedDate
		{
			get
			{
				return this._ApprovedDate;
			}
			set
			{
				if ((this._ApprovedDate != value))
				{
					this._ApprovedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleasedBy", DbType="VarChar(250)")]
		public string ReleasedBy
		{
			get
			{
				return this._ReleasedBy;
			}
			set
			{
				if ((this._ReleasedBy != value))
				{
					this._ReleasedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleasedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReleasedDate
		{
			get
			{
				return this._ReleasedDate;
			}
			set
			{
				if ((this._ReleasedDate != value))
				{
					this._ReleasedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackingNumber", DbType="VarChar(50)")]
		public string TrackingNumber
		{
			get
			{
				return this._TrackingNumber;
			}
			set
			{
				if ((this._TrackingNumber != value))
				{
					this._TrackingNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPerson2ADID", DbType="VarChar(50)")]
		public string SalesPerson2ADID
		{
			get
			{
				return this._SalesPerson2ADID;
			}
			set
			{
				if ((this._SalesPerson2ADID != value))
				{
					this._SalesPerson2ADID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateID", DbType="Int")]
		public System.Nullable<int> TemplateID
		{
			get
			{
				return this._TemplateID;
			}
			set
			{
				if ((this._TemplateID != value))
				{
					this._TemplateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidBy", DbType="VarChar(250)")]
		public string PaidBy
		{
			get
			{
				return this._PaidBy;
			}
			set
			{
				if ((this._PaidBy != value))
				{
					this._PaidBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaidDate
		{
			get
			{
				return this._PaidDate;
			}
			set
			{
				if ((this._PaidDate != value))
				{
					this._PaidDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollDate", DbType="Date")]
		public System.Nullable<System.DateTime> PayrollDate
		{
			get
			{
				return this._PayrollDate;
			}
			set
			{
				if ((this._PayrollDate != value))
				{
					this._PayrollDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPersonADID", DbType="VarChar(50)")]
		public string SalesPersonADID
		{
			get
			{
				return this._SalesPersonADID;
			}
			set
			{
				if ((this._SalesPersonADID != value))
				{
					this._SalesPersonADID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesOrder", DbType="VarChar(50)")]
		public string SalesOrder
		{
			get
			{
				return this._SalesOrder;
			}
			set
			{
				if ((this._SalesOrder != value))
				{
					this._SalesOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimatedShipDate", DbType="Date")]
		public System.Nullable<System.DateTime> EstimatedShipDate
		{
			get
			{
				return this._EstimatedShipDate;
			}
			set
			{
				if ((this._EstimatedShipDate != value))
				{
					this._EstimatedShipDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalPaymentDate", DbType="Date")]
		public System.Nullable<System.DateTime> FinalPaymentDate
		{
			get
			{
				return this._FinalPaymentDate;
			}
			set
			{
				if ((this._FinalPaymentDate != value))
				{
					this._FinalPaymentDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSMADID", DbType="VarChar(50)")]
		public string RSMADID
		{
			get
			{
				return this._RSMADID;
			}
			set
			{
				if ((this._RSMADID != value))
				{
					this._RSMADID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayRSMCommission", DbType="Bit")]
		public System.Nullable<bool> PayRSMCommission
		{
			get
			{
				return this._PayRSMCommission;
			}
			set
			{
				if ((this._PayRSMCommission != value))
				{
					this._PayRSMCommission = value;
				}
			}
		}
	}
	
	public partial class GetOrderItemsByOrderIDResult
	{
		
		private int _OrderItemID;
		
		private System.Nullable<int> _OrderID;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private int _ProductID;
		
		private System.Nullable<decimal> _ListPrice;
		
		public GetOrderItemsByOrderIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderItemID", DbType="Int NOT NULL")]
		public int OrderItemID
		{
			get
			{
				return this._OrderItemID;
			}
			set
			{
				if ((this._OrderItemID != value))
				{
					this._OrderItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int")]
		public System.Nullable<int> OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListPrice", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ListPrice
		{
			get
			{
				return this._ListPrice;
			}
			set
			{
				if ((this._ListPrice != value))
				{
					this._ListPrice = value;
				}
			}
		}
	}
	
	public partial class DeleteCustomerWOOrderResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public DeleteCustomerWOOrderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class DeleteProductWOOrderResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public DeleteProductWOOrderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetYTDBySalesmanOrderDateResult
	{
		
		private System.Nullable<decimal> _YTD;
		
		public GetYTDBySalesmanOrderDateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTD", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> YTD
		{
			get
			{
				return this._YTD;
			}
			set
			{
				if ((this._YTD != value))
				{
					this._YTD = value;
				}
			}
		}
	}
	
	public partial class DeleteSalesmanResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public DeleteSalesmanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class UpdateSalesmanResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public UpdateSalesmanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetgRIDcolumnsByUserResult
	{
		
		private string _username;
		
		private string _gridcolumns;
		
		public GetgRIDcolumnsByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridcolumns", DbType="VarChar(1500)")]
		public string gridcolumns
		{
			get
			{
				return this._gridcolumns;
			}
			set
			{
				if ((this._gridcolumns != value))
				{
					this._gridcolumns = value;
				}
			}
		}
	}
	
	public partial class GetViewsByUserResult
	{
		
		private string _gridname;
		
		private string _gridcolumns;
		
		public GetViewsByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridname", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string gridname
		{
			get
			{
				return this._gridname;
			}
			set
			{
				if ((this._gridname != value))
				{
					this._gridname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridcolumns", DbType="VarChar(1500)")]
		public string gridcolumns
		{
			get
			{
				return this._gridcolumns;
			}
			set
			{
				if ((this._gridcolumns != value))
				{
					this._gridcolumns = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
